# 1. Escolhe a imagem do Node
FROM node:18

# 2. Define onde os ficheiros vão ficar dentro do Linux/Docker
WORKDIR /usr/src/app

# 3. COPIA o package.json e o package-lock.json (se existir)
# O primeiro ponto é a tua pasta no Windows, o segundo é a pasta no Docker
COPY package*.json ./

# 4. Agora sim, instala as dependências
RUN npm install

# 5. Copia o resto do código (incluindo o server.js)
COPY . .

# 6. Abre a porta 3000
EXPOSE 3000

# 7. Comando para iniciar (que configurámos no package.json)
CMD ["npm", "start"]